import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/quickstart',
        'getting-started/install',
        'getting-started/pipe-mode',
        'getting-started/server-mode',
        'getting-started/first-query',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/ingest-data',
        'guides/search-and-filter',
        'guides/aggregations',
        'guides/field-extraction',
        'guides/json-processing',
        'guides/time-series',
        'guides/alerts',
        'guides/dashboards',
        'guides/materialized-views',
        'guides/saved-queries',
        'guides/live-tail',
        'guides/ctes-and-joins',
        'guides/scripting-and-pipes',
      ],
    },
    {
      type: 'category',
      label: 'SPL2 Reference',
      items: [
        'spl2/overview',
        {
          type: 'category',
          label: 'Commands',
          items: [
            'spl2/commands/from',
            'spl2/commands/search',
            'spl2/commands/where',
            'spl2/commands/eval',
            'spl2/commands/stats',
            'spl2/commands/sort',
            'spl2/commands/table',
            'spl2/commands/fields',
            'spl2/commands/rename',
            'spl2/commands/head',
            'spl2/commands/tail',
            'spl2/commands/dedup',
            'spl2/commands/rex',
            'spl2/commands/bin',
            'spl2/commands/timechart',
            'spl2/commands/top',
            'spl2/commands/rare',
            'spl2/commands/streamstats',
            'spl2/commands/eventstats',
            'spl2/commands/join',
            'spl2/commands/append',
            'spl2/commands/multisearch',
            'spl2/commands/transaction',
            'spl2/commands/xyseries',
            'spl2/commands/fillnull',
            {
              type: 'category',
              label: 'Format Parsing',
              items: [
                'spl2/commands/json-cmd',
                'spl2/commands/pack-json',
                'spl2/commands/unroll',
                'spl2/commands/unpack-json',
                'spl2/commands/unpack-logfmt',
                'spl2/commands/unpack-syslog',
                'spl2/commands/unpack-combined',
                'spl2/commands/unpack-clf',
                'spl2/commands/unpack-nginx-error',
                'spl2/commands/unpack-apache-error',
                'spl2/commands/unpack-cef',
                'spl2/commands/unpack-leef',
                'spl2/commands/unpack-kv',
                'spl2/commands/unpack-docker',
                'spl2/commands/unpack-redis',
                'spl2/commands/unpack-postgres',
                'spl2/commands/unpack-mysql-slow',
                'spl2/commands/unpack-haproxy',
                'spl2/commands/unpack-w3c',
                'spl2/commands/unpack-pattern',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Functions',
          items: [
            'spl2/functions/aggregation-functions',
            'spl2/functions/eval-functions',
            'spl2/functions/json-functions',
          ],
        },
        'spl2/data-types',
        'spl2/search-syntax',
        'spl2/time-ranges',
        'spl2/splunk-migration',
      ],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      items: [
        'cli/overview',
        'cli/query',
        'cli/ingest',
        'cli/tail',
        'cli/server',
        'cli/shortcuts',
        'cli/mv',
        'cli/alerts',
        'cli/config-cmd',
        'cli/shell',
        'cli/bench-demo',
        'cli/output-formats',
        'cli/completion',
        'cli/install',
      ],
    },
    {
      type: 'category',
      label: 'REST API',
      items: [
        'api/overview',
        'api/ingest',
        'api/query',
        'api/tail-histogram',
        'api/fields',
        'api/saved-queries',
        'api/alerts',
        'api/dashboards',
        'api/views',
        'api/server',
        'api/compatibility',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/overview',
        'configuration/server',
        'configuration/storage',
        'configuration/query',
        'configuration/ingest',
        'configuration/s3-tiering',
        'configuration/cluster',
        'configuration/environment-variables',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/single-node',
        'deployment/docker',
        'deployment/kubernetes',
        'deployment/small-cluster',
        'deployment/large-cluster',
        'deployment/s3-setup',
        'deployment/tls-auth',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      items: [
        'migration/from-splunk',
        'migration/from-elasticsearch',
        'migration/from-loki',
        'migration/from-grep',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/monitoring',
        'operations/backup-restore',
        'operations/retention',
        'operations/rebalancing',
        'operations/performance-tuning',
        'operations/troubleshooting',
        'operations/upgrading',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/storage-engine',
        'architecture/segment-format',
        'architecture/query-engine',
        'architecture/indexing',
        'architecture/distributed',
        'architecture/design-decisions',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/development-setup',
        'contributing/project-structure',
        'contributing/coding-guidelines',
      ],
    },
  ],
};

export default sidebars;
