package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/lynxbase/lynxdb/internal/ui"
	"github.com/lynxbase/lynxdb/pkg/config"
)

var (
	flagInitDataDir       string
	flagInitRetention     string
	flagInitNoInteractive bool
)

func init() {
	rootCmd.AddCommand(newInitCmd())
}

func newInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Set up LynxDB (interactive wizard)",
		Long:  `Walk through initial LynxDB setup: data directory, retention period, and config file creation.`,
		Example: `  lynxdb init
  lynxdb init --data-dir /data/lynxdb --retention 30d --no-interactive`,
		RunE: runInit,
	}

	cmd.Flags().StringVar(&flagInitDataDir, "data-dir", "", "Data directory (skip prompt)")
	cmd.Flags().StringVar(&flagInitRetention, "retention", "", "Retention period, e.g. 7d, 30d, 90d (skip prompt)")
	cmd.Flags().BoolVar(&flagInitNoInteractive, "no-interactive", false, "Non-interactive mode (use defaults + flags)")

	return cmd
}

func runInit(_ *cobra.Command, _ []string) error {
	defaults := config.DefaultConfig()
	cfgPath := config.DefaultConfigFilePath()
	interactive := !flagInitNoInteractive && isStdinTTY()

	// Data directory
	dataDir := flagInitDataDir
	if dataDir == "" && interactive {
		dataDir = promptDataDir(defaults.DataDir)
	}
	if dataDir == "" {
		dataDir = defaults.DataDir
	}

	// Retention
	retention := flagInitRetention
	if retention == "" && interactive {
		retention = promptRetention()
	}
	if retention == "" {
		retention = defaults.Retention.String()
	}

	// Validate retention before writing.
	retDuration, err := config.ParseDuration(retention)
	if err != nil {
		return fmt.Errorf("invalid retention %q: %w", retention, err)
	}

	if _, err := os.Stat(cfgPath); err == nil {
		if flagInitNoInteractive {
			return fmt.Errorf("config already exists: %s", cfgPath)
		}
		if !confirmAction(fmt.Sprintf("Config already exists at %s. Overwrite?", cfgPath)) {
			fmt.Fprintln(os.Stderr, "  Aborted.")

			return nil
		}
	}

	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return fmt.Errorf("create data directory: %w", err)
	}

	if err := writeInitConfig(cfgPath, dataDir, retDuration); err != nil {
		return err
	}

	if interactive {
		fmt.Fprintln(os.Stderr)
	}
	printSuccess("Created config:   %s", cfgPath)
	printSuccess("Created data dir: %s", dataDir)

	printNextSteps(
		"lynxdb server     Start the server",
		"lynxdb demo       Generate sample data to explore",
	)
	fmt.Fprintln(os.Stderr)

	return nil
}

// writeInitConfig writes a minimal, readable config file with only the
// user-selected values. This is intentionally NOT a full config dump —
// users see exactly what they chose, and can add more settings later.
func writeInitConfig(path, dataDir string, retention config.Duration) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create config directory: %w", err)
	}

	var buf strings.Builder
	buf.WriteString("# LynxDB configuration\n")
	buf.WriteString("# Generated by 'lynxdb init'. See 'lynxdb config' for all settings.\n\n")
	fmt.Fprintf(&buf, "data_dir: %s\n", dataDir)
	fmt.Fprintf(&buf, "retention: %s\n", retention.String())

	if err := os.WriteFile(path, []byte(buf.String()), 0o600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	return nil
}

// promptDataDir asks the user for a data directory path interactively.
func promptDataDir(defaultDir string) string {
	// Show ~ instead of full home path for readability.
	displayDefault := defaultDir
	if home, _ := os.UserHomeDir(); home != "" {
		displayDefault = strings.Replace(displayDefault, home, "~", 1)
	}

	t := ui.Stderr
	fmt.Fprintf(os.Stderr, "\n  Where should LynxDB store data?\n")
	fmt.Fprintf(os.Stderr, "  Path [%s]: ", t.Dim.Render(displayDefault))

	scanner := bufio.NewScanner(os.Stdin)
	if scanner.Scan() {
		text := strings.TrimSpace(scanner.Text())
		if text != "" {
			return expandHome(text)
		}
	}

	return defaultDir
}

// promptRetention asks the user for a retention period interactively.
func promptRetention() string {
	t := ui.Stderr
	fmt.Fprintf(os.Stderr, "\n  Default retention period?\n")
	fmt.Fprintf(os.Stderr, "  %s 7 days %s\n", t.Bold.Render("[1]"), t.Dim.Render("(default)"))
	fmt.Fprintf(os.Stderr, "  %s 30 days\n", t.Bold.Render("[2]"))
	fmt.Fprintf(os.Stderr, "  %s 90 days\n", t.Bold.Render("[3]"))
	fmt.Fprintf(os.Stderr, "  %s Custom\n", t.Bold.Render("[4]"))
	fmt.Fprintf(os.Stderr, "  Choice [1]: ")

	scanner := bufio.NewScanner(os.Stdin)
	if !scanner.Scan() {
		return "7d"
	}

	text := strings.TrimSpace(scanner.Text())
	switch text {
	case "", "1":
		return "7d"
	case "2":
		return "30d"
	case "3":
		return "90d"
	case "4":
		fmt.Fprintf(os.Stderr, "  Retention (e.g. 14d, 60d): ")
		if scanner.Scan() {
			custom := strings.TrimSpace(scanner.Text())
			if custom != "" {
				return custom
			}
		}

		return "7d"
	default:
		// Accept raw duration strings typed directly (e.g. "14d").
		if _, err := config.ParseDuration(text); err == nil {
			return text
		}

		return "7d"
	}
}

// expandHome replaces a leading "~/" with the user's home directory.
func expandHome(path string) string {
	if strings.HasPrefix(path, "~/") {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, path[2:])
		}
	}

	return path
}
