// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: cluster.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AckLevel specifies the durability guarantee for ingest batches.
type AckLevel int32

const (
	AckLevel_ACK_NONE AckLevel = 0 // Fire-and-forget, no durability guarantee.
	AckLevel_ACK_ONE  AckLevel = 1 // Acknowledged after local commit (default).
	AckLevel_ACK_ALL  AckLevel = 2 // Acknowledged after all ISR replicas confirm.
)

// Enum value maps for AckLevel.
var (
	AckLevel_name = map[int32]string{
		0: "ACK_NONE",
		1: "ACK_ONE",
		2: "ACK_ALL",
	}
	AckLevel_value = map[string]int32{
		"ACK_NONE": 0,
		"ACK_ONE":  1,
		"ACK_ALL":  2,
	}
)

func (x AckLevel) Enum() *AckLevel {
	p := new(AckLevel)
	*p = x
	return p
}

func (x AckLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_proto_enumTypes[0].Descriptor()
}

func (AckLevel) Type() protoreflect.EnumType {
	return &file_cluster_proto_enumTypes[0]
}

func (x AckLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckLevel.Descriptor instead.
func (AckLevel) EnumDescriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

type HandshakeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr            string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	GrpcAddr        string                 `protobuf:"bytes,4,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	Roles           []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Version         string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HandshakeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HandshakeRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *HandshakeRequest) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *HandshakeRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *HandshakeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	LeaderId        string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddr      string                 `protobuf:"bytes,3,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	ShardMap        []byte                 `protobuf:"bytes,4,opt,name=shard_map,json=shardMap,proto3" json:"shard_map,omitempty"` // msgpack-encoded ShardMap
	ShardMapEpoch   uint64                 `protobuf:"varint,5,opt,name=shard_map_epoch,json=shardMapEpoch,proto3" json:"shard_map_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HandshakeResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *HandshakeResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

func (x *HandshakeResponse) GetShardMap() []byte {
	if x != nil {
		return x.ShardMap
	}
	return nil
}

func (x *HandshakeResponse) GetShardMapEpoch() uint64 {
	if x != nil {
		return x.ShardMapEpoch
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Resources     *NodeResourceReport    `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetResources() *NodeResourceReport {
	if x != nil {
		return x.Resources
	}
	return nil
}

type NodeResourceReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent       float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedBytes  int64                  `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes int64                  `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskUsedBytes    int64                  `protobuf:"varint,4,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes   int64                  `protobuf:"varint,5,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	ActiveQueries    int64                  `protobuf:"varint,6,opt,name=active_queries,json=activeQueries,proto3" json:"active_queries,omitempty"`
	IngestRateEps    int64                  `protobuf:"varint,7,opt,name=ingest_rate_eps,json=ingestRateEps,proto3" json:"ingest_rate_eps,omitempty"` // events per second
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeResourceReport) Reset() {
	*x = NodeResourceReport{}
	mi := &file_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResourceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResourceReport) ProtoMessage() {}

func (x *NodeResourceReport) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResourceReport.ProtoReflect.Descriptor instead.
func (*NodeResourceReport) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *NodeResourceReport) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeResourceReport) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeResourceReport) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeResourceReport) GetDiskUsedBytes() int64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *NodeResourceReport) GetDiskTotalBytes() int64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *NodeResourceReport) GetActiveQueries() int64 {
	if x != nil {
		return x.ActiveQueries
	}
	return 0
}

func (x *NodeResourceReport) GetIngestRateEps() int64 {
	if x != nil {
		return x.IngestRateEps
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type WatchShardMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentEpoch  uint64                 `protobuf:"varint,1,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"` // client's current epoch; server sends if newer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchShardMapRequest) Reset() {
	*x = WatchShardMapRequest{}
	mi := &file_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchShardMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchShardMapRequest) ProtoMessage() {}

func (x *WatchShardMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchShardMapRequest.ProtoReflect.Descriptor instead.
func (*WatchShardMapRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *WatchShardMapRequest) GetCurrentEpoch() uint64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

type ShardMapUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShardMap       []byte                 `protobuf:"bytes,1,opt,name=shard_map,json=shardMap,proto3" json:"shard_map,omitempty"` // msgpack-encoded ShardMap
	Epoch          uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	FieldCatalog   []byte                 `protobuf:"bytes,3,opt,name=field_catalog,json=fieldCatalog,proto3" json:"field_catalog,omitempty"`       // msgpack-encoded []GlobalFieldInfo (piggybacked)
	SourceRegistry []byte                 `protobuf:"bytes,4,opt,name=source_registry,json=sourceRegistry,proto3" json:"source_registry,omitempty"` // msgpack-encoded []GlobalSourceInfo (piggybacked)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShardMapUpdate) Reset() {
	*x = ShardMapUpdate{}
	mi := &file_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardMapUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardMapUpdate) ProtoMessage() {}

func (x *ShardMapUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardMapUpdate.ProtoReflect.Descriptor instead.
func (*ShardMapUpdate) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ShardMapUpdate) GetShardMap() []byte {
	if x != nil {
		return x.ShardMap
	}
	return nil
}

func (x *ShardMapUpdate) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ShardMapUpdate) GetFieldCatalog() []byte {
	if x != nil {
		return x.FieldCatalog
	}
	return nil
}

func (x *ShardMapUpdate) GetSourceRegistry() []byte {
	if x != nil {
		return x.SourceRegistry
	}
	return nil
}

type RenewLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ShardId       string                 `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseRequest) Reset() {
	*x = RenewLeaseRequest{}
	mi := &file_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseRequest) ProtoMessage() {}

func (x *RenewLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewLeaseRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *RenewLeaseRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RenewLeaseRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *RenewLeaseRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type RenewLeaseResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Granted         bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	ExpiresAtUnixNs int64                  `protobuf:"varint,2,opt,name=expires_at_unix_ns,json=expiresAtUnixNs,proto3" json:"expires_at_unix_ns,omitempty"`
	LeaderAddr      string                 `protobuf:"bytes,3,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"` // set when this node is not the leader (redirect)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenewLeaseResponse) Reset() {
	*x = RenewLeaseResponse{}
	mi := &file_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseResponse) ProtoMessage() {}

func (x *RenewLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewLeaseResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *RenewLeaseResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *RenewLeaseResponse) GetExpiresAtUnixNs() int64 {
	if x != nil {
		return x.ExpiresAtUnixNs
	}
	return 0
}

func (x *RenewLeaseResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

type RequestCompactionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ShardId        string                 `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	CatalogVersion uint64                 `protobuf:"varint,3,opt,name=catalog_version,json=catalogVersion,proto3" json:"catalog_version,omitempty"`
	InputParts     []string               `protobuf:"bytes,4,rep,name=input_parts,json=inputParts,proto3" json:"input_parts,omitempty"`
	TargetLevel    int32                  `protobuf:"varint,5,opt,name=target_level,json=targetLevel,proto3" json:"target_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestCompactionRequest) Reset() {
	*x = RequestCompactionRequest{}
	mi := &file_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCompactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCompactionRequest) ProtoMessage() {}

func (x *RequestCompactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCompactionRequest.ProtoReflect.Descriptor instead.
func (*RequestCompactionRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *RequestCompactionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RequestCompactionRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *RequestCompactionRequest) GetCatalogVersion() uint64 {
	if x != nil {
		return x.CatalogVersion
	}
	return 0
}

func (x *RequestCompactionRequest) GetInputParts() []string {
	if x != nil {
		return x.InputParts
	}
	return nil
}

func (x *RequestCompactionRequest) GetTargetLevel() int32 {
	if x != nil {
		return x.TargetLevel
	}
	return 0
}

type RequestCompactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,3,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"` // set when this node is not the leader (redirect)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCompactionResponse) Reset() {
	*x = RequestCompactionResponse{}
	mi := &file_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCompactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCompactionResponse) ProtoMessage() {}

func (x *RequestCompactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCompactionResponse.ProtoReflect.Descriptor instead.
func (*RequestCompactionResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *RequestCompactionResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *RequestCompactionResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RequestCompactionResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

type ReleaseCompactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	OutputParts   []string               `protobuf:"bytes,3,rep,name=output_parts,json=outputParts,proto3" json:"output_parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCompactionRequest) Reset() {
	*x = ReleaseCompactionRequest{}
	mi := &file_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCompactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCompactionRequest) ProtoMessage() {}

func (x *ReleaseCompactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCompactionRequest.ProtoReflect.Descriptor instead.
func (*ReleaseCompactionRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseCompactionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReleaseCompactionRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseCompactionRequest) GetOutputParts() []string {
	if x != nil {
		return x.OutputParts
	}
	return nil
}

type ReleaseCompactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCompactionResponse) Reset() {
	*x = ReleaseCompactionResponse{}
	mi := &file_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCompactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCompactionResponse) ProtoMessage() {}

func (x *ReleaseCompactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCompactionResponse.ProtoReflect.Descriptor instead.
func (*ReleaseCompactionResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseCompactionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// ProposeDrain initiates draining a shard from a node.
type ProposeDrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeDrainRequest) Reset() {
	*x = ProposeDrainRequest{}
	mi := &file_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeDrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeDrainRequest) ProtoMessage() {}

func (x *ProposeDrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeDrainRequest.ProtoReflect.Descriptor instead.
func (*ProposeDrainRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *ProposeDrainRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ProposeDrainRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ProposeDrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"` // set when this node is not the leader (redirect)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeDrainResponse) Reset() {
	*x = ProposeDrainResponse{}
	mi := &file_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeDrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeDrainResponse) ProtoMessage() {}

func (x *ProposeDrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeDrainResponse.ProtoReflect.Descriptor instead.
func (*ProposeDrainResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *ProposeDrainResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ProposeDrainResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

// CompleteDrain marks a shard drain as complete, allowing failover to a new primary.
type CompleteDrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NewPrimaryId  string                 `protobuf:"bytes,3,opt,name=new_primary_id,json=newPrimaryId,proto3" json:"new_primary_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteDrainRequest) Reset() {
	*x = CompleteDrainRequest{}
	mi := &file_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteDrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteDrainRequest) ProtoMessage() {}

func (x *CompleteDrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteDrainRequest.ProtoReflect.Descriptor instead.
func (*CompleteDrainRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *CompleteDrainRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *CompleteDrainRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CompleteDrainRequest) GetNewPrimaryId() string {
	if x != nil {
		return x.NewPrimaryId
	}
	return ""
}

type CompleteDrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"` // set when this node is not the leader (redirect)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteDrainResponse) Reset() {
	*x = CompleteDrainResponse{}
	mi := &file_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteDrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteDrainResponse) ProtoMessage() {}

func (x *CompleteDrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteDrainResponse.ProtoReflect.Descriptor instead.
func (*CompleteDrainResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *CompleteDrainResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CompleteDrainResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

type FieldDeltaProto struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Count         int64                   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	TopValues     []*FieldValueEntryProto `protobuf:"bytes,4,rep,name=top_values,json=topValues,proto3" json:"top_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDeltaProto) Reset() {
	*x = FieldDeltaProto{}
	mi := &file_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDeltaProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDeltaProto) ProtoMessage() {}

func (x *FieldDeltaProto) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDeltaProto.ProtoReflect.Descriptor instead.
func (*FieldDeltaProto) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *FieldDeltaProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldDeltaProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldDeltaProto) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FieldDeltaProto) GetTopValues() []*FieldValueEntryProto {
	if x != nil {
		return x.TopValues
	}
	return nil
}

type FieldValueEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValueEntryProto) Reset() {
	*x = FieldValueEntryProto{}
	mi := &file_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValueEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValueEntryProto) ProtoMessage() {}

func (x *FieldValueEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValueEntryProto.ProtoReflect.Descriptor instead.
func (*FieldValueEntryProto) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *FieldValueEntryProto) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FieldValueEntryProto) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReportFieldCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Fields        []*FieldDeltaProto     `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFieldCatalogRequest) Reset() {
	*x = ReportFieldCatalogRequest{}
	mi := &file_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFieldCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFieldCatalogRequest) ProtoMessage() {}

func (x *ReportFieldCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFieldCatalogRequest.ProtoReflect.Descriptor instead.
func (*ReportFieldCatalogRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{19}
}

func (x *ReportFieldCatalogRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportFieldCatalogRequest) GetFields() []*FieldDeltaProto {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ReportFieldCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFieldCatalogResponse) Reset() {
	*x = ReportFieldCatalogResponse{}
	mi := &file_cluster_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFieldCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFieldCatalogResponse) ProtoMessage() {}

func (x *ReportFieldCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFieldCatalogResponse.ProtoReflect.Descriptor instead.
func (*ReportFieldCatalogResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{20}
}

func (x *ReportFieldCatalogResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SourceDeltaProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EventCount     int64                  `protobuf:"varint,2,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	LastSeenUnixNs int64                  `protobuf:"varint,3,opt,name=last_seen_unix_ns,json=lastSeenUnixNs,proto3" json:"last_seen_unix_ns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SourceDeltaProto) Reset() {
	*x = SourceDeltaProto{}
	mi := &file_cluster_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceDeltaProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceDeltaProto) ProtoMessage() {}

func (x *SourceDeltaProto) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceDeltaProto.ProtoReflect.Descriptor instead.
func (*SourceDeltaProto) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{21}
}

func (x *SourceDeltaProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceDeltaProto) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *SourceDeltaProto) GetLastSeenUnixNs() int64 {
	if x != nil {
		return x.LastSeenUnixNs
	}
	return 0
}

type ReportSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Sources       []*SourceDeltaProto    `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSourcesRequest) Reset() {
	*x = ReportSourcesRequest{}
	mi := &file_cluster_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSourcesRequest) ProtoMessage() {}

func (x *ReportSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSourcesRequest.ProtoReflect.Descriptor instead.
func (*ReportSourcesRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{22}
}

func (x *ReportSourcesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportSourcesRequest) GetSources() []*SourceDeltaProto {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ReportSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSourcesResponse) Reset() {
	*x = ReportSourcesResponse{}
	mi := &file_cluster_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSourcesResponse) ProtoMessage() {}

func (x *ReportSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSourcesResponse.ProtoReflect.Descriptor instead.
func (*ReportSourcesResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{23}
}

func (x *ReportSourcesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type AssignAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	QueryNodeIds  []string               `protobuf:"bytes,2,rep,name=query_node_ids,json=queryNodeIds,proto3" json:"query_node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAlertRequest) Reset() {
	*x = AssignAlertRequest{}
	mi := &file_cluster_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAlertRequest) ProtoMessage() {}

func (x *AssignAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAlertRequest.ProtoReflect.Descriptor instead.
func (*AssignAlertRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{24}
}

func (x *AssignAlertRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AssignAlertRequest) GetQueryNodeIds() []string {
	if x != nil {
		return x.QueryNodeIds
	}
	return nil
}

type AssignAlertResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	AssignedNodeId string                 `protobuf:"bytes,2,opt,name=assigned_node_id,json=assignedNodeId,proto3" json:"assigned_node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignAlertResponse) Reset() {
	*x = AssignAlertResponse{}
	mi := &file_cluster_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAlertResponse) ProtoMessage() {}

func (x *AssignAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAlertResponse.ProtoReflect.Descriptor instead.
func (*AssignAlertResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{25}
}

func (x *AssignAlertResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AssignAlertResponse) GetAssignedNodeId() string {
	if x != nil {
		return x.AssignedNodeId
	}
	return ""
}

type ReportAlertFiredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	FiredAtUnixNs int64                  `protobuf:"varint,2,opt,name=fired_at_unix_ns,json=firedAtUnixNs,proto3" json:"fired_at_unix_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAlertFiredRequest) Reset() {
	*x = ReportAlertFiredRequest{}
	mi := &file_cluster_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAlertFiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAlertFiredRequest) ProtoMessage() {}

func (x *ReportAlertFiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAlertFiredRequest.ProtoReflect.Descriptor instead.
func (*ReportAlertFiredRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{26}
}

func (x *ReportAlertFiredRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *ReportAlertFiredRequest) GetFiredAtUnixNs() int64 {
	if x != nil {
		return x.FiredAtUnixNs
	}
	return 0
}

type ReportAlertFiredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAlertFiredResponse) Reset() {
	*x = ReportAlertFiredResponse{}
	mi := &file_cluster_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAlertFiredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAlertFiredResponse) ProtoMessage() {}

func (x *ReportAlertFiredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAlertFiredResponse.ProtoReflect.Descriptor instead.
func (*ReportAlertFiredResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{27}
}

func (x *ReportAlertFiredResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RegisterViewRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Query             string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CoordinatorNodeId string                 `protobuf:"bytes,4,opt,name=coordinator_node_id,json=coordinatorNodeId,proto3" json:"coordinator_node_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterViewRequest) Reset() {
	*x = RegisterViewRequest{}
	mi := &file_cluster_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterViewRequest) ProtoMessage() {}

func (x *RegisterViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterViewRequest.ProtoReflect.Descriptor instead.
func (*RegisterViewRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{28}
}

func (x *RegisterViewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterViewRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RegisterViewRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterViewRequest) GetCoordinatorNodeId() string {
	if x != nil {
		return x.CoordinatorNodeId
	}
	return ""
}

type RegisterViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterViewResponse) Reset() {
	*x = RegisterViewResponse{}
	mi := &file_cluster_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterViewResponse) ProtoMessage() {}

func (x *RegisterViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterViewResponse.ProtoReflect.Descriptor instead.
func (*RegisterViewResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{29}
}

func (x *RegisterViewResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type IngestBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Events        []byte                 `protobuf:"bytes,2,opt,name=events,proto3" json:"events,omitempty"` // msgpack-encoded []*event.Event
	LeaseEpoch    uint64                 `protobuf:"varint,3,opt,name=lease_epoch,json=leaseEpoch,proto3" json:"lease_epoch,omitempty"`
	BatchSeq      uint64                 `protobuf:"varint,4,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"`                                 // monotonic batch sequence for dedup
	AckLevel      AckLevel               `protobuf:"varint,5,opt,name=ack_level,json=ackLevel,proto3,enum=lynxdb.cluster.v1.AckLevel" json:"ack_level,omitempty"` // requested durability level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchRequest) Reset() {
	*x = IngestBatchRequest{}
	mi := &file_cluster_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchRequest) ProtoMessage() {}

func (x *IngestBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestBatchRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{30}
}

func (x *IngestBatchRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *IngestBatchRequest) GetEvents() []byte {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *IngestBatchRequest) GetLeaseEpoch() uint64 {
	if x != nil {
		return x.LeaseEpoch
	}
	return 0
}

func (x *IngestBatchRequest) GetBatchSeq() uint64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

func (x *IngestBatchRequest) GetAckLevel() AckLevel {
	if x != nil {
		return x.AckLevel
	}
	return AckLevel_ACK_NONE
}

type IngestBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	BatchSeq      uint64                 `protobuf:"varint,2,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"` // confirmed batch sequence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchResponse) Reset() {
	*x = IngestBatchResponse{}
	mi := &file_cluster_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchResponse) ProtoMessage() {}

func (x *IngestBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchResponse.ProtoReflect.Descriptor instead.
func (*IngestBatchResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{31}
}

func (x *IngestBatchResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *IngestBatchResponse) GetBatchSeq() uint64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

// ReplicateEntry carries a batch of events to replica nodes for ISR replication.
type ReplicateEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Events        []byte                 `protobuf:"bytes,2,opt,name=events,proto3" json:"events,omitempty"`                      // msgpack-encoded []*event.Event
	BatchSeq      uint64                 `protobuf:"varint,3,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"` // batch sequence for ordering and dedup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateEntry) Reset() {
	*x = ReplicateEntry{}
	mi := &file_cluster_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateEntry) ProtoMessage() {}

func (x *ReplicateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateEntry.ProtoReflect.Descriptor instead.
func (*ReplicateEntry) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{32}
}

func (x *ReplicateEntry) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ReplicateEntry) GetEvents() []byte {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReplicateEntry) GetBatchSeq() uint64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

type ReplicateBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LastBatchSeq  uint64                 `protobuf:"varint,2,opt,name=last_batch_seq,json=lastBatchSeq,proto3" json:"last_batch_seq,omitempty"` // highest replicated batch sequence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateBatchResponse) Reset() {
	*x = ReplicateBatchResponse{}
	mi := &file_cluster_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateBatchResponse) ProtoMessage() {}

func (x *ReplicateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateBatchResponse.ProtoReflect.Descriptor instead.
func (*ReplicateBatchResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{33}
}

func (x *ReplicateBatchResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReplicateBatchResponse) GetLastBatchSeq() uint64 {
	if x != nil {
		return x.LastBatchSeq
	}
	return 0
}

type ExecuteQueryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ShardId        string                 `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	FromUnixNs     int64                  `protobuf:"varint,3,opt,name=from_unix_ns,json=fromUnixNs,proto3" json:"from_unix_ns,omitempty"`
	ToUnixNs       int64                  `protobuf:"varint,4,opt,name=to_unix_ns,json=toUnixNs,proto3" json:"to_unix_ns,omitempty"`
	PartialAggSpec []byte                 `protobuf:"bytes,5,opt,name=partial_agg_spec,json=partialAggSpec,proto3" json:"partial_agg_spec,omitempty"` // msgpack-encoded PartialAggSpec (nil = full scan)
	RequiredCols   []string               `protobuf:"bytes,6,rep,name=required_cols,json=requiredCols,proto3" json:"required_cols,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_cluster_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{34}
}

func (x *ExecuteQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteQueryRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ExecuteQueryRequest) GetFromUnixNs() int64 {
	if x != nil {
		return x.FromUnixNs
	}
	return 0
}

func (x *ExecuteQueryRequest) GetToUnixNs() int64 {
	if x != nil {
		return x.ToUnixNs
	}
	return 0
}

func (x *ExecuteQueryRequest) GetPartialAggSpec() []byte {
	if x != nil {
		return x.PartialAggSpec
	}
	return nil
}

func (x *ExecuteQueryRequest) GetRequiredCols() []string {
	if x != nil {
		return x.RequiredCols
	}
	return nil
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []byte                 `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"` // msgpack-encoded row
	IsPartial     bool                   `protobuf:"varint,2,opt,name=is_partial,json=isPartial,proto3" json:"is_partial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_cluster_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{35}
}

func (x *QueryResult) GetRow() []byte {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *QueryResult) GetIsPartial() bool {
	if x != nil {
		return x.IsPartial
	}
	return false
}

// PartCommittedNotification informs query nodes that a new part is available for queries.
type PartCommittedNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	PartId        string                 `protobuf:"bytes,2,opt,name=part_id,json=partId,proto3" json:"part_id,omitempty"`
	MinTimeUnixNs int64                  `protobuf:"varint,3,opt,name=min_time_unix_ns,json=minTimeUnixNs,proto3" json:"min_time_unix_ns,omitempty"`
	MaxTimeUnixNs int64                  `protobuf:"varint,4,opt,name=max_time_unix_ns,json=maxTimeUnixNs,proto3" json:"max_time_unix_ns,omitempty"`
	EventCount    int64                  `protobuf:"varint,5,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	S3Key         string                 `protobuf:"bytes,6,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`           // S3 object key for the part file
	BatchSeq      uint64                 `protobuf:"varint,7,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"` // highest batch sequence included in this part
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartCommittedNotification) Reset() {
	*x = PartCommittedNotification{}
	mi := &file_cluster_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartCommittedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartCommittedNotification) ProtoMessage() {}

func (x *PartCommittedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartCommittedNotification.ProtoReflect.Descriptor instead.
func (*PartCommittedNotification) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{36}
}

func (x *PartCommittedNotification) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *PartCommittedNotification) GetPartId() string {
	if x != nil {
		return x.PartId
	}
	return ""
}

func (x *PartCommittedNotification) GetMinTimeUnixNs() int64 {
	if x != nil {
		return x.MinTimeUnixNs
	}
	return 0
}

func (x *PartCommittedNotification) GetMaxTimeUnixNs() int64 {
	if x != nil {
		return x.MaxTimeUnixNs
	}
	return 0
}

func (x *PartCommittedNotification) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *PartCommittedNotification) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *PartCommittedNotification) GetBatchSeq() uint64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

type PartCommittedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartCommittedResponse) Reset() {
	*x = PartCommittedResponse{}
	mi := &file_cluster_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartCommittedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartCommittedResponse) ProtoMessage() {}

func (x *PartCommittedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartCommittedResponse.ProtoReflect.Descriptor instead.
func (*PartCommittedResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{37}
}

func (x *PartCommittedResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SubscribeTailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	FromUnixNs    int64                  `protobuf:"varint,2,opt,name=from_unix_ns,json=fromUnixNs,proto3" json:"from_unix_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTailRequest) Reset() {
	*x = SubscribeTailRequest{}
	mi := &file_cluster_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTailRequest) ProtoMessage() {}

func (x *SubscribeTailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTailRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTailRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{38}
}

func (x *SubscribeTailRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SubscribeTailRequest) GetFromUnixNs() int64 {
	if x != nil {
		return x.FromUnixNs
	}
	return 0
}

type TailEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         []byte                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`                                 // msgpack-encoded event fields
	WatermarkNs   int64                  `protobuf:"varint,2,opt,name=watermark_ns,json=watermarkNs,proto3" json:"watermark_ns,omitempty"` // current node watermark
	IsCatchup     bool                   `protobuf:"varint,3,opt,name=is_catchup,json=isCatchup,proto3" json:"is_catchup,omitempty"`       // true for historical events during catchup phase
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailEvent) Reset() {
	*x = TailEvent{}
	mi := &file_cluster_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailEvent) ProtoMessage() {}

func (x *TailEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailEvent.ProtoReflect.Descriptor instead.
func (*TailEvent) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{39}
}

func (x *TailEvent) GetEvent() []byte {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TailEvent) GetWatermarkNs() int64 {
	if x != nil {
		return x.WatermarkNs
	}
	return 0
}

func (x *TailEvent) GetIsCatchup() bool {
	if x != nil {
		return x.IsCatchup
	}
	return false
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\x11lynxdb.cluster.v1\"\xb7\x01\n" +
	"\x10HandshakeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12\x1b\n" +
	"\tgrpc_addr\x18\x04 \x01(\tR\bgrpcAddr\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"\xc1\x01\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x1f\n" +
	"\vleader_addr\x18\x03 \x01(\tR\n" +
	"leaderAddr\x12\x1b\n" +
	"\tshard_map\x18\x04 \x01(\fR\bshardMap\x12&\n" +
	"\x0fshard_map_epoch\x18\x05 \x01(\x04R\rshardMapEpoch\"p\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12C\n" +
	"\tresources\x18\x02 \x01(\v2%.lynxdb.cluster.v1.NodeResourceReportR\tresources\"\xb0\x02\n" +
	"\x12NodeResourceReport\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x03R\x10memoryTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x04 \x01(\x03R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x05 \x01(\x03R\x0ediskTotalBytes\x12%\n" +
	"\x0eactive_queries\x18\x06 \x01(\x03R\ractiveQueries\x12&\n" +
	"\x0fingest_rate_eps\x18\a \x01(\x03R\ringestRateEps\"@\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\";\n" +
	"\x14WatchShardMapRequest\x12#\n" +
	"\rcurrent_epoch\x18\x01 \x01(\x04R\fcurrentEpoch\"\x91\x01\n" +
	"\x0eShardMapUpdate\x12\x1b\n" +
	"\tshard_map\x18\x01 \x01(\fR\bshardMap\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12#\n" +
	"\rfield_catalog\x18\x03 \x01(\fR\ffieldCatalog\x12'\n" +
	"\x0fsource_registry\x18\x04 \x01(\fR\x0esourceRegistry\"]\n" +
	"\x11RenewLeaseRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\tR\ashardId\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\"|\n" +
	"\x12RenewLeaseResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12+\n" +
	"\x12expires_at_unix_ns\x18\x02 \x01(\x03R\x0fexpiresAtUnixNs\x12\x1f\n" +
	"\vleader_addr\x18\x03 \x01(\tR\n" +
	"leaderAddr\"\xbb\x01\n" +
	"\x18RequestCompactionRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\tR\ashardId\x12'\n" +
	"\x0fcatalog_version\x18\x03 \x01(\x04R\x0ecatalogVersion\x12\x1f\n" +
	"\vinput_parts\x18\x04 \x03(\tR\n" +
	"inputParts\x12!\n" +
	"\ftarget_level\x18\x05 \x01(\x05R\vtargetLevel\"o\n" +
	"\x19RequestCompactionResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vleader_addr\x18\x03 \x01(\tR\n" +
	"leaderAddr\"p\n" +
	"\x18ReleaseCompactionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\foutput_parts\x18\x03 \x03(\tR\voutputParts\"+\n" +
	"\x19ReleaseCompactionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"I\n" +
	"\x13ProposeDrainRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"G\n" +
	"\x14ProposeDrainResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\"p\n" +
	"\x14CompleteDrainRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12$\n" +
	"\x0enew_primary_id\x18\x03 \x01(\tR\fnewPrimaryId\"H\n" +
	"\x15CompleteDrainResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\"\x97\x01\n" +
	"\x0fFieldDeltaProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12F\n" +
	"\n" +
	"top_values\x18\x04 \x03(\v2'.lynxdb.cluster.v1.FieldValueEntryProtoR\ttopValues\"B\n" +
	"\x14FieldValueEntryProto\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"p\n" +
	"\x19ReportFieldCatalogRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12:\n" +
	"\x06fields\x18\x02 \x03(\v2\".lynxdb.cluster.v1.FieldDeltaProtoR\x06fields\",\n" +
	"\x1aReportFieldCatalogResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"r\n" +
	"\x10SourceDeltaProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vevent_count\x18\x02 \x01(\x03R\n" +
	"eventCount\x12)\n" +
	"\x11last_seen_unix_ns\x18\x03 \x01(\x03R\x0elastSeenUnixNs\"n\n" +
	"\x14ReportSourcesRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12=\n" +
	"\asources\x18\x02 \x03(\v2#.lynxdb.cluster.v1.SourceDeltaProtoR\asources\"'\n" +
	"\x15ReportSourcesResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"U\n" +
	"\x12AssignAlertRequest\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12$\n" +
	"\x0equery_node_ids\x18\x02 \x03(\tR\fqueryNodeIds\"O\n" +
	"\x13AssignAlertResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12(\n" +
	"\x10assigned_node_id\x18\x02 \x01(\tR\x0eassignedNodeId\"]\n" +
	"\x17ReportAlertFiredRequest\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12'\n" +
	"\x10fired_at_unix_ns\x18\x02 \x01(\x03R\rfiredAtUnixNs\"*\n" +
	"\x18ReportAlertFiredResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x87\x01\n" +
	"\x13RegisterViewRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12.\n" +
	"\x13coordinator_node_id\x18\x04 \x01(\tR\x11coordinatorNodeId\"&\n" +
	"\x14RegisterViewResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xbf\x01\n" +
	"\x12IngestBatchRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x16\n" +
	"\x06events\x18\x02 \x01(\fR\x06events\x12\x1f\n" +
	"\vlease_epoch\x18\x03 \x01(\x04R\n" +
	"leaseEpoch\x12\x1b\n" +
	"\tbatch_seq\x18\x04 \x01(\x04R\bbatchSeq\x128\n" +
	"\tack_level\x18\x05 \x01(\x0e2\x1b.lynxdb.cluster.v1.AckLevelR\backLevel\"B\n" +
	"\x13IngestBatchResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tbatch_seq\x18\x02 \x01(\x04R\bbatchSeq\"`\n" +
	"\x0eReplicateEntry\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x16\n" +
	"\x06events\x18\x02 \x01(\fR\x06events\x12\x1b\n" +
	"\tbatch_seq\x18\x03 \x01(\x04R\bbatchSeq\"N\n" +
	"\x16ReplicateBatchResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12$\n" +
	"\x0elast_batch_seq\x18\x02 \x01(\x04R\flastBatchSeq\"\xd5\x01\n" +
	"\x13ExecuteQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\tR\ashardId\x12 \n" +
	"\ffrom_unix_ns\x18\x03 \x01(\x03R\n" +
	"fromUnixNs\x12\x1c\n" +
	"\n" +
	"to_unix_ns\x18\x04 \x01(\x03R\btoUnixNs\x12(\n" +
	"\x10partial_agg_spec\x18\x05 \x01(\fR\x0epartialAggSpec\x12#\n" +
	"\rrequired_cols\x18\x06 \x03(\tR\frequiredCols\">\n" +
	"\vQueryResult\x12\x10\n" +
	"\x03row\x18\x01 \x01(\fR\x03row\x12\x1d\n" +
	"\n" +
	"is_partial\x18\x02 \x01(\bR\tisPartial\"\xf6\x01\n" +
	"\x19PartCommittedNotification\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x17\n" +
	"\apart_id\x18\x02 \x01(\tR\x06partId\x12'\n" +
	"\x10min_time_unix_ns\x18\x03 \x01(\x03R\rminTimeUnixNs\x12'\n" +
	"\x10max_time_unix_ns\x18\x04 \x01(\x03R\rmaxTimeUnixNs\x12\x1f\n" +
	"\vevent_count\x18\x05 \x01(\x03R\n" +
	"eventCount\x12\x15\n" +
	"\x06s3_key\x18\x06 \x01(\tR\x05s3Key\x12\x1b\n" +
	"\tbatch_seq\x18\a \x01(\x04R\bbatchSeq\"'\n" +
	"\x15PartCommittedResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"N\n" +
	"\x14SubscribeTailRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12 \n" +
	"\ffrom_unix_ns\x18\x02 \x01(\x03R\n" +
	"fromUnixNs\"c\n" +
	"\tTailEvent\x12\x14\n" +
	"\x05event\x18\x01 \x01(\fR\x05event\x12!\n" +
	"\fwatermark_ns\x18\x02 \x01(\x03R\vwatermarkNs\x12\x1d\n" +
	"\n" +
	"is_catchup\x18\x03 \x01(\bR\tisCatchup*2\n" +
	"\bAckLevel\x12\f\n" +
	"\bACK_NONE\x10\x00\x12\v\n" +
	"\aACK_ONE\x10\x01\x12\v\n" +
	"\aACK_ALL\x10\x022\x9f\n" +
	"\n" +
	"\vMetaService\x12V\n" +
	"\tHandshake\x12#.lynxdb.cluster.v1.HandshakeRequest\x1a$.lynxdb.cluster.v1.HandshakeResponse\x12V\n" +
	"\tHeartbeat\x12#.lynxdb.cluster.v1.HeartbeatRequest\x1a$.lynxdb.cluster.v1.HeartbeatResponse\x12]\n" +
	"\rWatchShardMap\x12'.lynxdb.cluster.v1.WatchShardMapRequest\x1a!.lynxdb.cluster.v1.ShardMapUpdate0\x01\x12Y\n" +
	"\n" +
	"RenewLease\x12$.lynxdb.cluster.v1.RenewLeaseRequest\x1a%.lynxdb.cluster.v1.RenewLeaseResponse\x12n\n" +
	"\x11RequestCompaction\x12+.lynxdb.cluster.v1.RequestCompactionRequest\x1a,.lynxdb.cluster.v1.RequestCompactionResponse\x12n\n" +
	"\x11ReleaseCompaction\x12+.lynxdb.cluster.v1.ReleaseCompactionRequest\x1a,.lynxdb.cluster.v1.ReleaseCompactionResponse\x12_\n" +
	"\fProposeDrain\x12&.lynxdb.cluster.v1.ProposeDrainRequest\x1a'.lynxdb.cluster.v1.ProposeDrainResponse\x12b\n" +
	"\rCompleteDrain\x12'.lynxdb.cluster.v1.CompleteDrainRequest\x1a(.lynxdb.cluster.v1.CompleteDrainResponse\x12q\n" +
	"\x12ReportFieldCatalog\x12,.lynxdb.cluster.v1.ReportFieldCatalogRequest\x1a-.lynxdb.cluster.v1.ReportFieldCatalogResponse\x12b\n" +
	"\rReportSources\x12'.lynxdb.cluster.v1.ReportSourcesRequest\x1a(.lynxdb.cluster.v1.ReportSourcesResponse\x12\\\n" +
	"\vAssignAlert\x12%.lynxdb.cluster.v1.AssignAlertRequest\x1a&.lynxdb.cluster.v1.AssignAlertResponse\x12k\n" +
	"\x10ReportAlertFired\x12*.lynxdb.cluster.v1.ReportAlertFiredRequest\x1a+.lynxdb.cluster.v1.ReportAlertFiredResponse\x12_\n" +
	"\fRegisterView\x12&.lynxdb.cluster.v1.RegisterViewRequest\x1a'.lynxdb.cluster.v1.RegisterViewResponse2\xcf\x01\n" +
	"\rIngestService\x12\\\n" +
	"\vIngestBatch\x12%.lynxdb.cluster.v1.IngestBatchRequest\x1a&.lynxdb.cluster.v1.IngestBatchResponse\x12`\n" +
	"\x0eReplicateBatch\x12!.lynxdb.cluster.v1.ReplicateEntry\x1a).lynxdb.cluster.v1.ReplicateBatchResponse(\x012\xb1\x02\n" +
	"\fQueryService\x12X\n" +
	"\fExecuteQuery\x12&.lynxdb.cluster.v1.ExecuteQueryRequest\x1a\x1e.lynxdb.cluster.v1.QueryResult0\x01\x12m\n" +
	"\x13NotifyPartCommitted\x12,.lynxdb.cluster.v1.PartCommittedNotification\x1a(.lynxdb.cluster.v1.PartCommittedResponse\x12X\n" +
	"\rSubscribeTail\x12'.lynxdb.cluster.v1.SubscribeTailRequest\x1a\x1c.lynxdb.cluster.v1.TailEvent0\x01B2Z0github.com/lynxbase/lynxdb/pkg/cluster/rpc/protob\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_cluster_proto_goTypes = []any{
	(AckLevel)(0),                      // 0: lynxdb.cluster.v1.AckLevel
	(*HandshakeRequest)(nil),           // 1: lynxdb.cluster.v1.HandshakeRequest
	(*HandshakeResponse)(nil),          // 2: lynxdb.cluster.v1.HandshakeResponse
	(*HeartbeatRequest)(nil),           // 3: lynxdb.cluster.v1.HeartbeatRequest
	(*NodeResourceReport)(nil),         // 4: lynxdb.cluster.v1.NodeResourceReport
	(*HeartbeatResponse)(nil),          // 5: lynxdb.cluster.v1.HeartbeatResponse
	(*WatchShardMapRequest)(nil),       // 6: lynxdb.cluster.v1.WatchShardMapRequest
	(*ShardMapUpdate)(nil),             // 7: lynxdb.cluster.v1.ShardMapUpdate
	(*RenewLeaseRequest)(nil),          // 8: lynxdb.cluster.v1.RenewLeaseRequest
	(*RenewLeaseResponse)(nil),         // 9: lynxdb.cluster.v1.RenewLeaseResponse
	(*RequestCompactionRequest)(nil),   // 10: lynxdb.cluster.v1.RequestCompactionRequest
	(*RequestCompactionResponse)(nil),  // 11: lynxdb.cluster.v1.RequestCompactionResponse
	(*ReleaseCompactionRequest)(nil),   // 12: lynxdb.cluster.v1.ReleaseCompactionRequest
	(*ReleaseCompactionResponse)(nil),  // 13: lynxdb.cluster.v1.ReleaseCompactionResponse
	(*ProposeDrainRequest)(nil),        // 14: lynxdb.cluster.v1.ProposeDrainRequest
	(*ProposeDrainResponse)(nil),       // 15: lynxdb.cluster.v1.ProposeDrainResponse
	(*CompleteDrainRequest)(nil),       // 16: lynxdb.cluster.v1.CompleteDrainRequest
	(*CompleteDrainResponse)(nil),      // 17: lynxdb.cluster.v1.CompleteDrainResponse
	(*FieldDeltaProto)(nil),            // 18: lynxdb.cluster.v1.FieldDeltaProto
	(*FieldValueEntryProto)(nil),       // 19: lynxdb.cluster.v1.FieldValueEntryProto
	(*ReportFieldCatalogRequest)(nil),  // 20: lynxdb.cluster.v1.ReportFieldCatalogRequest
	(*ReportFieldCatalogResponse)(nil), // 21: lynxdb.cluster.v1.ReportFieldCatalogResponse
	(*SourceDeltaProto)(nil),           // 22: lynxdb.cluster.v1.SourceDeltaProto
	(*ReportSourcesRequest)(nil),       // 23: lynxdb.cluster.v1.ReportSourcesRequest
	(*ReportSourcesResponse)(nil),      // 24: lynxdb.cluster.v1.ReportSourcesResponse
	(*AssignAlertRequest)(nil),         // 25: lynxdb.cluster.v1.AssignAlertRequest
	(*AssignAlertResponse)(nil),        // 26: lynxdb.cluster.v1.AssignAlertResponse
	(*ReportAlertFiredRequest)(nil),    // 27: lynxdb.cluster.v1.ReportAlertFiredRequest
	(*ReportAlertFiredResponse)(nil),   // 28: lynxdb.cluster.v1.ReportAlertFiredResponse
	(*RegisterViewRequest)(nil),        // 29: lynxdb.cluster.v1.RegisterViewRequest
	(*RegisterViewResponse)(nil),       // 30: lynxdb.cluster.v1.RegisterViewResponse
	(*IngestBatchRequest)(nil),         // 31: lynxdb.cluster.v1.IngestBatchRequest
	(*IngestBatchResponse)(nil),        // 32: lynxdb.cluster.v1.IngestBatchResponse
	(*ReplicateEntry)(nil),             // 33: lynxdb.cluster.v1.ReplicateEntry
	(*ReplicateBatchResponse)(nil),     // 34: lynxdb.cluster.v1.ReplicateBatchResponse
	(*ExecuteQueryRequest)(nil),        // 35: lynxdb.cluster.v1.ExecuteQueryRequest
	(*QueryResult)(nil),                // 36: lynxdb.cluster.v1.QueryResult
	(*PartCommittedNotification)(nil),  // 37: lynxdb.cluster.v1.PartCommittedNotification
	(*PartCommittedResponse)(nil),      // 38: lynxdb.cluster.v1.PartCommittedResponse
	(*SubscribeTailRequest)(nil),       // 39: lynxdb.cluster.v1.SubscribeTailRequest
	(*TailEvent)(nil),                  // 40: lynxdb.cluster.v1.TailEvent
}
var file_cluster_proto_depIdxs = []int32{
	4,  // 0: lynxdb.cluster.v1.HeartbeatRequest.resources:type_name -> lynxdb.cluster.v1.NodeResourceReport
	19, // 1: lynxdb.cluster.v1.FieldDeltaProto.top_values:type_name -> lynxdb.cluster.v1.FieldValueEntryProto
	18, // 2: lynxdb.cluster.v1.ReportFieldCatalogRequest.fields:type_name -> lynxdb.cluster.v1.FieldDeltaProto
	22, // 3: lynxdb.cluster.v1.ReportSourcesRequest.sources:type_name -> lynxdb.cluster.v1.SourceDeltaProto
	0,  // 4: lynxdb.cluster.v1.IngestBatchRequest.ack_level:type_name -> lynxdb.cluster.v1.AckLevel
	1,  // 5: lynxdb.cluster.v1.MetaService.Handshake:input_type -> lynxdb.cluster.v1.HandshakeRequest
	3,  // 6: lynxdb.cluster.v1.MetaService.Heartbeat:input_type -> lynxdb.cluster.v1.HeartbeatRequest
	6,  // 7: lynxdb.cluster.v1.MetaService.WatchShardMap:input_type -> lynxdb.cluster.v1.WatchShardMapRequest
	8,  // 8: lynxdb.cluster.v1.MetaService.RenewLease:input_type -> lynxdb.cluster.v1.RenewLeaseRequest
	10, // 9: lynxdb.cluster.v1.MetaService.RequestCompaction:input_type -> lynxdb.cluster.v1.RequestCompactionRequest
	12, // 10: lynxdb.cluster.v1.MetaService.ReleaseCompaction:input_type -> lynxdb.cluster.v1.ReleaseCompactionRequest
	14, // 11: lynxdb.cluster.v1.MetaService.ProposeDrain:input_type -> lynxdb.cluster.v1.ProposeDrainRequest
	16, // 12: lynxdb.cluster.v1.MetaService.CompleteDrain:input_type -> lynxdb.cluster.v1.CompleteDrainRequest
	20, // 13: lynxdb.cluster.v1.MetaService.ReportFieldCatalog:input_type -> lynxdb.cluster.v1.ReportFieldCatalogRequest
	23, // 14: lynxdb.cluster.v1.MetaService.ReportSources:input_type -> lynxdb.cluster.v1.ReportSourcesRequest
	25, // 15: lynxdb.cluster.v1.MetaService.AssignAlert:input_type -> lynxdb.cluster.v1.AssignAlertRequest
	27, // 16: lynxdb.cluster.v1.MetaService.ReportAlertFired:input_type -> lynxdb.cluster.v1.ReportAlertFiredRequest
	29, // 17: lynxdb.cluster.v1.MetaService.RegisterView:input_type -> lynxdb.cluster.v1.RegisterViewRequest
	31, // 18: lynxdb.cluster.v1.IngestService.IngestBatch:input_type -> lynxdb.cluster.v1.IngestBatchRequest
	33, // 19: lynxdb.cluster.v1.IngestService.ReplicateBatch:input_type -> lynxdb.cluster.v1.ReplicateEntry
	35, // 20: lynxdb.cluster.v1.QueryService.ExecuteQuery:input_type -> lynxdb.cluster.v1.ExecuteQueryRequest
	37, // 21: lynxdb.cluster.v1.QueryService.NotifyPartCommitted:input_type -> lynxdb.cluster.v1.PartCommittedNotification
	39, // 22: lynxdb.cluster.v1.QueryService.SubscribeTail:input_type -> lynxdb.cluster.v1.SubscribeTailRequest
	2,  // 23: lynxdb.cluster.v1.MetaService.Handshake:output_type -> lynxdb.cluster.v1.HandshakeResponse
	5,  // 24: lynxdb.cluster.v1.MetaService.Heartbeat:output_type -> lynxdb.cluster.v1.HeartbeatResponse
	7,  // 25: lynxdb.cluster.v1.MetaService.WatchShardMap:output_type -> lynxdb.cluster.v1.ShardMapUpdate
	9,  // 26: lynxdb.cluster.v1.MetaService.RenewLease:output_type -> lynxdb.cluster.v1.RenewLeaseResponse
	11, // 27: lynxdb.cluster.v1.MetaService.RequestCompaction:output_type -> lynxdb.cluster.v1.RequestCompactionResponse
	13, // 28: lynxdb.cluster.v1.MetaService.ReleaseCompaction:output_type -> lynxdb.cluster.v1.ReleaseCompactionResponse
	15, // 29: lynxdb.cluster.v1.MetaService.ProposeDrain:output_type -> lynxdb.cluster.v1.ProposeDrainResponse
	17, // 30: lynxdb.cluster.v1.MetaService.CompleteDrain:output_type -> lynxdb.cluster.v1.CompleteDrainResponse
	21, // 31: lynxdb.cluster.v1.MetaService.ReportFieldCatalog:output_type -> lynxdb.cluster.v1.ReportFieldCatalogResponse
	24, // 32: lynxdb.cluster.v1.MetaService.ReportSources:output_type -> lynxdb.cluster.v1.ReportSourcesResponse
	26, // 33: lynxdb.cluster.v1.MetaService.AssignAlert:output_type -> lynxdb.cluster.v1.AssignAlertResponse
	28, // 34: lynxdb.cluster.v1.MetaService.ReportAlertFired:output_type -> lynxdb.cluster.v1.ReportAlertFiredResponse
	30, // 35: lynxdb.cluster.v1.MetaService.RegisterView:output_type -> lynxdb.cluster.v1.RegisterViewResponse
	32, // 36: lynxdb.cluster.v1.IngestService.IngestBatch:output_type -> lynxdb.cluster.v1.IngestBatchResponse
	34, // 37: lynxdb.cluster.v1.IngestService.ReplicateBatch:output_type -> lynxdb.cluster.v1.ReplicateBatchResponse
	36, // 38: lynxdb.cluster.v1.QueryService.ExecuteQuery:output_type -> lynxdb.cluster.v1.QueryResult
	38, // 39: lynxdb.cluster.v1.QueryService.NotifyPartCommitted:output_type -> lynxdb.cluster.v1.PartCommittedResponse
	40, // 40: lynxdb.cluster.v1.QueryService.SubscribeTail:output_type -> lynxdb.cluster.v1.TailEvent
	23, // [23:41] is the sub-list for method output_type
	5,  // [5:23] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		EnumInfos:         file_cluster_proto_enumTypes,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
