// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: cluster.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetaService_Handshake_FullMethodName          = "/lynxdb.cluster.v1.MetaService/Handshake"
	MetaService_Heartbeat_FullMethodName          = "/lynxdb.cluster.v1.MetaService/Heartbeat"
	MetaService_WatchShardMap_FullMethodName      = "/lynxdb.cluster.v1.MetaService/WatchShardMap"
	MetaService_RenewLease_FullMethodName         = "/lynxdb.cluster.v1.MetaService/RenewLease"
	MetaService_RequestCompaction_FullMethodName  = "/lynxdb.cluster.v1.MetaService/RequestCompaction"
	MetaService_ReleaseCompaction_FullMethodName  = "/lynxdb.cluster.v1.MetaService/ReleaseCompaction"
	MetaService_ProposeDrain_FullMethodName       = "/lynxdb.cluster.v1.MetaService/ProposeDrain"
	MetaService_CompleteDrain_FullMethodName      = "/lynxdb.cluster.v1.MetaService/CompleteDrain"
	MetaService_ReportFieldCatalog_FullMethodName = "/lynxdb.cluster.v1.MetaService/ReportFieldCatalog"
	MetaService_ReportSources_FullMethodName      = "/lynxdb.cluster.v1.MetaService/ReportSources"
	MetaService_AssignAlert_FullMethodName        = "/lynxdb.cluster.v1.MetaService/AssignAlert"
	MetaService_ReportAlertFired_FullMethodName   = "/lynxdb.cluster.v1.MetaService/ReportAlertFired"
	MetaService_RegisterView_FullMethodName       = "/lynxdb.cluster.v1.MetaService/RegisterView"
)

// MetaServiceClient is the client API for MetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetaService handles cluster metadata operations via the Raft leader.
type MetaServiceClient interface {
	// Handshake registers a node with the cluster and returns the current shard map.
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Heartbeat reports node health and resource usage to the meta leader.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// WatchShardMap streams shard map updates to the caller.
	WatchShardMap(ctx context.Context, in *WatchShardMapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardMapUpdate], error)
	// RenewLease extends the validity of a shard lease.
	RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error)
	// RequestCompaction requests permission to compact a shard.
	RequestCompaction(ctx context.Context, in *RequestCompactionRequest, opts ...grpc.CallOption) (*RequestCompactionResponse, error)
	// ReleaseCompaction releases a compaction lock held on a shard.
	ReleaseCompaction(ctx context.Context, in *ReleaseCompactionRequest, opts ...grpc.CallOption) (*ReleaseCompactionResponse, error)
	// ProposeDrain requests to drain a shard from a node before removal.
	ProposeDrain(ctx context.Context, in *ProposeDrainRequest, opts ...grpc.CallOption) (*ProposeDrainResponse, error)
	// CompleteDrain marks a shard drain as complete, transitions to new primary.
	CompleteDrain(ctx context.Context, in *CompleteDrainRequest, opts ...grpc.CallOption) (*CompleteDrainResponse, error)
	// ReportFieldCatalog reports local field catalog deltas from an ingest node.
	ReportFieldCatalog(ctx context.Context, in *ReportFieldCatalogRequest, opts ...grpc.CallOption) (*ReportFieldCatalogResponse, error)
	// ReportSources reports local source registry deltas from an ingest node.
	ReportSources(ctx context.Context, in *ReportSourcesRequest, opts ...grpc.CallOption) (*ReportSourcesResponse, error)
	// AssignAlert assigns an alert to a query node via rendezvous hashing.
	AssignAlert(ctx context.Context, in *AssignAlertRequest, opts ...grpc.CallOption) (*AssignAlertResponse, error)
	// ReportAlertFired records the timestamp of an alert trigger.
	ReportAlertFired(ctx context.Context, in *ReportAlertFiredRequest, opts ...grpc.CallOption) (*ReportAlertFiredResponse, error)
	// RegisterView registers or updates a materialized view definition.
	RegisterView(ctx context.Context, in *RegisterViewRequest, opts ...grpc.CallOption) (*RegisterViewResponse, error)
}

type metaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaServiceClient(cc grpc.ClientConnInterface) MetaServiceClient {
	return &metaServiceClient{cc}
}

func (c *metaServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, MetaService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MetaService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) WatchShardMap(ctx context.Context, in *WatchShardMapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardMapUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetaService_ServiceDesc.Streams[0], MetaService_WatchShardMap_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchShardMapRequest, ShardMapUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetaService_WatchShardMapClient = grpc.ServerStreamingClient[ShardMapUpdate]

func (c *metaServiceClient) RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewLeaseResponse)
	err := c.cc.Invoke(ctx, MetaService_RenewLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) RequestCompaction(ctx context.Context, in *RequestCompactionRequest, opts ...grpc.CallOption) (*RequestCompactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestCompactionResponse)
	err := c.cc.Invoke(ctx, MetaService_RequestCompaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) ReleaseCompaction(ctx context.Context, in *ReleaseCompactionRequest, opts ...grpc.CallOption) (*ReleaseCompactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseCompactionResponse)
	err := c.cc.Invoke(ctx, MetaService_ReleaseCompaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) ProposeDrain(ctx context.Context, in *ProposeDrainRequest, opts ...grpc.CallOption) (*ProposeDrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeDrainResponse)
	err := c.cc.Invoke(ctx, MetaService_ProposeDrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) CompleteDrain(ctx context.Context, in *CompleteDrainRequest, opts ...grpc.CallOption) (*CompleteDrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteDrainResponse)
	err := c.cc.Invoke(ctx, MetaService_CompleteDrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) ReportFieldCatalog(ctx context.Context, in *ReportFieldCatalogRequest, opts ...grpc.CallOption) (*ReportFieldCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportFieldCatalogResponse)
	err := c.cc.Invoke(ctx, MetaService_ReportFieldCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) ReportSources(ctx context.Context, in *ReportSourcesRequest, opts ...grpc.CallOption) (*ReportSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSourcesResponse)
	err := c.cc.Invoke(ctx, MetaService_ReportSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) AssignAlert(ctx context.Context, in *AssignAlertRequest, opts ...grpc.CallOption) (*AssignAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignAlertResponse)
	err := c.cc.Invoke(ctx, MetaService_AssignAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) ReportAlertFired(ctx context.Context, in *ReportAlertFiredRequest, opts ...grpc.CallOption) (*ReportAlertFiredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAlertFiredResponse)
	err := c.cc.Invoke(ctx, MetaService_ReportAlertFired_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) RegisterView(ctx context.Context, in *RegisterViewRequest, opts ...grpc.CallOption) (*RegisterViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterViewResponse)
	err := c.cc.Invoke(ctx, MetaService_RegisterView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServiceServer is the server API for MetaService service.
// All implementations must embed UnimplementedMetaServiceServer
// for forward compatibility.
//
// MetaService handles cluster metadata operations via the Raft leader.
type MetaServiceServer interface {
	// Handshake registers a node with the cluster and returns the current shard map.
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Heartbeat reports node health and resource usage to the meta leader.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// WatchShardMap streams shard map updates to the caller.
	WatchShardMap(*WatchShardMapRequest, grpc.ServerStreamingServer[ShardMapUpdate]) error
	// RenewLease extends the validity of a shard lease.
	RenewLease(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error)
	// RequestCompaction requests permission to compact a shard.
	RequestCompaction(context.Context, *RequestCompactionRequest) (*RequestCompactionResponse, error)
	// ReleaseCompaction releases a compaction lock held on a shard.
	ReleaseCompaction(context.Context, *ReleaseCompactionRequest) (*ReleaseCompactionResponse, error)
	// ProposeDrain requests to drain a shard from a node before removal.
	ProposeDrain(context.Context, *ProposeDrainRequest) (*ProposeDrainResponse, error)
	// CompleteDrain marks a shard drain as complete, transitions to new primary.
	CompleteDrain(context.Context, *CompleteDrainRequest) (*CompleteDrainResponse, error)
	// ReportFieldCatalog reports local field catalog deltas from an ingest node.
	ReportFieldCatalog(context.Context, *ReportFieldCatalogRequest) (*ReportFieldCatalogResponse, error)
	// ReportSources reports local source registry deltas from an ingest node.
	ReportSources(context.Context, *ReportSourcesRequest) (*ReportSourcesResponse, error)
	// AssignAlert assigns an alert to a query node via rendezvous hashing.
	AssignAlert(context.Context, *AssignAlertRequest) (*AssignAlertResponse, error)
	// ReportAlertFired records the timestamp of an alert trigger.
	ReportAlertFired(context.Context, *ReportAlertFiredRequest) (*ReportAlertFiredResponse, error)
	// RegisterView registers or updates a materialized view definition.
	RegisterView(context.Context, *RegisterViewRequest) (*RegisterViewResponse, error)
	mustEmbedUnimplementedMetaServiceServer()
}

// UnimplementedMetaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaServiceServer struct{}

func (UnimplementedMetaServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedMetaServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMetaServiceServer) WatchShardMap(*WatchShardMapRequest, grpc.ServerStreamingServer[ShardMapUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchShardMap not implemented")
}
func (UnimplementedMetaServiceServer) RenewLease(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewLease not implemented")
}
func (UnimplementedMetaServiceServer) RequestCompaction(context.Context, *RequestCompactionRequest) (*RequestCompactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCompaction not implemented")
}
func (UnimplementedMetaServiceServer) ReleaseCompaction(context.Context, *ReleaseCompactionRequest) (*ReleaseCompactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseCompaction not implemented")
}
func (UnimplementedMetaServiceServer) ProposeDrain(context.Context, *ProposeDrainRequest) (*ProposeDrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeDrain not implemented")
}
func (UnimplementedMetaServiceServer) CompleteDrain(context.Context, *CompleteDrainRequest) (*CompleteDrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteDrain not implemented")
}
func (UnimplementedMetaServiceServer) ReportFieldCatalog(context.Context, *ReportFieldCatalogRequest) (*ReportFieldCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFieldCatalog not implemented")
}
func (UnimplementedMetaServiceServer) ReportSources(context.Context, *ReportSourcesRequest) (*ReportSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSources not implemented")
}
func (UnimplementedMetaServiceServer) AssignAlert(context.Context, *AssignAlertRequest) (*AssignAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignAlert not implemented")
}
func (UnimplementedMetaServiceServer) ReportAlertFired(context.Context, *ReportAlertFiredRequest) (*ReportAlertFiredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAlertFired not implemented")
}
func (UnimplementedMetaServiceServer) RegisterView(context.Context, *RegisterViewRequest) (*RegisterViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterView not implemented")
}
func (UnimplementedMetaServiceServer) mustEmbedUnimplementedMetaServiceServer() {}
func (UnimplementedMetaServiceServer) testEmbeddedByValue()                     {}

// UnsafeMetaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaServiceServer will
// result in compilation errors.
type UnsafeMetaServiceServer interface {
	mustEmbedUnimplementedMetaServiceServer()
}

func RegisterMetaServiceServer(s grpc.ServiceRegistrar, srv MetaServiceServer) {
	// If the following call panics, it indicates UnimplementedMetaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetaService_ServiceDesc, srv)
}

func _MetaService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_WatchShardMap_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchShardMapRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetaServiceServer).WatchShardMap(m, &grpc.GenericServerStream[WatchShardMapRequest, ShardMapUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetaService_WatchShardMapServer = grpc.ServerStreamingServer[ShardMapUpdate]

func _MetaService_RenewLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).RenewLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_RenewLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).RenewLease(ctx, req.(*RenewLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_RequestCompaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCompactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).RequestCompaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_RequestCompaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).RequestCompaction(ctx, req.(*RequestCompactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_ReleaseCompaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseCompactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).ReleaseCompaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_ReleaseCompaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).ReleaseCompaction(ctx, req.(*ReleaseCompactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_ProposeDrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeDrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).ProposeDrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_ProposeDrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).ProposeDrain(ctx, req.(*ProposeDrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_CompleteDrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteDrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).CompleteDrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_CompleteDrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).CompleteDrain(ctx, req.(*CompleteDrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_ReportFieldCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportFieldCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).ReportFieldCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_ReportFieldCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).ReportFieldCatalog(ctx, req.(*ReportFieldCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_ReportSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).ReportSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_ReportSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).ReportSources(ctx, req.(*ReportSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_AssignAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).AssignAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_AssignAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).AssignAlert(ctx, req.(*AssignAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_ReportAlertFired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportAlertFiredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).ReportAlertFired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_ReportAlertFired_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).ReportAlertFired(ctx, req.(*ReportAlertFiredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_RegisterView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).RegisterView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_RegisterView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).RegisterView(ctx, req.(*RegisterViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaService_ServiceDesc is the grpc.ServiceDesc for MetaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lynxdb.cluster.v1.MetaService",
	HandlerType: (*MetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _MetaService_Handshake_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _MetaService_Heartbeat_Handler,
		},
		{
			MethodName: "RenewLease",
			Handler:    _MetaService_RenewLease_Handler,
		},
		{
			MethodName: "RequestCompaction",
			Handler:    _MetaService_RequestCompaction_Handler,
		},
		{
			MethodName: "ReleaseCompaction",
			Handler:    _MetaService_ReleaseCompaction_Handler,
		},
		{
			MethodName: "ProposeDrain",
			Handler:    _MetaService_ProposeDrain_Handler,
		},
		{
			MethodName: "CompleteDrain",
			Handler:    _MetaService_CompleteDrain_Handler,
		},
		{
			MethodName: "ReportFieldCatalog",
			Handler:    _MetaService_ReportFieldCatalog_Handler,
		},
		{
			MethodName: "ReportSources",
			Handler:    _MetaService_ReportSources_Handler,
		},
		{
			MethodName: "AssignAlert",
			Handler:    _MetaService_AssignAlert_Handler,
		},
		{
			MethodName: "ReportAlertFired",
			Handler:    _MetaService_ReportAlertFired_Handler,
		},
		{
			MethodName: "RegisterView",
			Handler:    _MetaService_RegisterView_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchShardMap",
			Handler:       _MetaService_WatchShardMap_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cluster.proto",
}

const (
	IngestService_IngestBatch_FullMethodName    = "/lynxdb.cluster.v1.IngestService/IngestBatch"
	IngestService_ReplicateBatch_FullMethodName = "/lynxdb.cluster.v1.IngestService/ReplicateBatch"
)

// IngestServiceClient is the client API for IngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IngestService handles distributed event ingestion.
type IngestServiceClient interface {
	// IngestBatch forwards an event batch to the shard owner.
	IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error)
	// ReplicateBatch streams event entries to replica nodes for ISR replication.
	ReplicateBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReplicateEntry, ReplicateBatchResponse], error)
}

type ingestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestServiceClient(cc grpc.ClientConnInterface) IngestServiceClient {
	return &ingestServiceClient{cc}
}

func (c *ingestServiceClient) IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestBatchResponse)
	err := c.cc.Invoke(ctx, IngestService_IngestBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) ReplicateBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReplicateEntry, ReplicateBatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestService_ServiceDesc.Streams[0], IngestService_ReplicateBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplicateEntry, ReplicateBatchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_ReplicateBatchClient = grpc.ClientStreamingClient[ReplicateEntry, ReplicateBatchResponse]

// IngestServiceServer is the server API for IngestService service.
// All implementations must embed UnimplementedIngestServiceServer
// for forward compatibility.
//
// IngestService handles distributed event ingestion.
type IngestServiceServer interface {
	// IngestBatch forwards an event batch to the shard owner.
	IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error)
	// ReplicateBatch streams event entries to replica nodes for ISR replication.
	ReplicateBatch(grpc.ClientStreamingServer[ReplicateEntry, ReplicateBatchResponse]) error
	mustEmbedUnimplementedIngestServiceServer()
}

// UnimplementedIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServiceServer struct{}

func (UnimplementedIngestServiceServer) IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestBatch not implemented")
}
func (UnimplementedIngestServiceServer) ReplicateBatch(grpc.ClientStreamingServer[ReplicateEntry, ReplicateBatchResponse]) error {
	return status.Error(codes.Unimplemented, "method ReplicateBatch not implemented")
}
func (UnimplementedIngestServiceServer) mustEmbedUnimplementedIngestServiceServer() {}
func (UnimplementedIngestServiceServer) testEmbeddedByValue()                       {}

// UnsafeIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServiceServer will
// result in compilation errors.
type UnsafeIngestServiceServer interface {
	mustEmbedUnimplementedIngestServiceServer()
}

func RegisterIngestServiceServer(s grpc.ServiceRegistrar, srv IngestServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestService_ServiceDesc, srv)
}

func _IngestService_IngestBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).IngestBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_IngestBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).IngestBatch(ctx, req.(*IngestBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_ReplicateBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServiceServer).ReplicateBatch(&grpc.GenericServerStream[ReplicateEntry, ReplicateBatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_ReplicateBatchServer = grpc.ClientStreamingServer[ReplicateEntry, ReplicateBatchResponse]

// IngestService_ServiceDesc is the grpc.ServiceDesc for IngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lynxdb.cluster.v1.IngestService",
	HandlerType: (*IngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestBatch",
			Handler:    _IngestService_IngestBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReplicateBatch",
			Handler:       _IngestService_ReplicateBatch_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "cluster.proto",
}

const (
	QueryService_ExecuteQuery_FullMethodName        = "/lynxdb.cluster.v1.QueryService/ExecuteQuery"
	QueryService_NotifyPartCommitted_FullMethodName = "/lynxdb.cluster.v1.QueryService/NotifyPartCommitted"
	QueryService_SubscribeTail_FullMethodName       = "/lynxdb.cluster.v1.QueryService/SubscribeTail"
)

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QueryService handles distributed query execution.
type QueryServiceClient interface {
	// ExecuteQuery runs a partial query on a shard and streams results.
	ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult], error)
	// NotifyPartCommitted informs query nodes that a new part is available.
	NotifyPartCommitted(ctx context.Context, in *PartCommittedNotification, opts ...grpc.CallOption) (*PartCommittedResponse, error)
	// SubscribeTail opens a live tail stream for real-time event delivery.
	SubscribeTail(ctx context.Context, in *SubscribeTailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TailEvent], error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[0], QueryService_ExecuteQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteQueryRequest, QueryResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_ExecuteQueryClient = grpc.ServerStreamingClient[QueryResult]

func (c *queryServiceClient) NotifyPartCommitted(ctx context.Context, in *PartCommittedNotification, opts ...grpc.CallOption) (*PartCommittedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartCommittedResponse)
	err := c.cc.Invoke(ctx, QueryService_NotifyPartCommitted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) SubscribeTail(ctx context.Context, in *SubscribeTailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TailEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[1], QueryService_SubscribeTail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeTailRequest, TailEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_SubscribeTailClient = grpc.ServerStreamingClient[TailEvent]

// QueryServiceServer is the server API for QueryService service.
// All implementations must embed UnimplementedQueryServiceServer
// for forward compatibility.
//
// QueryService handles distributed query execution.
type QueryServiceServer interface {
	// ExecuteQuery runs a partial query on a shard and streams results.
	ExecuteQuery(*ExecuteQueryRequest, grpc.ServerStreamingServer[QueryResult]) error
	// NotifyPartCommitted informs query nodes that a new part is available.
	NotifyPartCommitted(context.Context, *PartCommittedNotification) (*PartCommittedResponse, error)
	// SubscribeTail opens a live tail stream for real-time event delivery.
	SubscribeTail(*SubscribeTailRequest, grpc.ServerStreamingServer[TailEvent]) error
	mustEmbedUnimplementedQueryServiceServer()
}

// UnimplementedQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServiceServer struct{}

func (UnimplementedQueryServiceServer) ExecuteQuery(*ExecuteQueryRequest, grpc.ServerStreamingServer[QueryResult]) error {
	return status.Error(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedQueryServiceServer) NotifyPartCommitted(context.Context, *PartCommittedNotification) (*PartCommittedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPartCommitted not implemented")
}
func (UnimplementedQueryServiceServer) SubscribeTail(*SubscribeTailRequest, grpc.ServerStreamingServer[TailEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeTail not implemented")
}
func (UnimplementedQueryServiceServer) mustEmbedUnimplementedQueryServiceServer() {}
func (UnimplementedQueryServiceServer) testEmbeddedByValue()                      {}

// UnsafeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServiceServer will
// result in compilation errors.
type UnsafeQueryServiceServer interface {
	mustEmbedUnimplementedQueryServiceServer()
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {
	// If the following call panics, it indicates UnimplementedQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryService_ServiceDesc, srv)
}

func _QueryService_ExecuteQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).ExecuteQuery(m, &grpc.GenericServerStream[ExecuteQueryRequest, QueryResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_ExecuteQueryServer = grpc.ServerStreamingServer[QueryResult]

func _QueryService_NotifyPartCommitted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartCommittedNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).NotifyPartCommitted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_NotifyPartCommitted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).NotifyPartCommitted(ctx, req.(*PartCommittedNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_SubscribeTail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTailRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).SubscribeTail(m, &grpc.GenericServerStream[SubscribeTailRequest, TailEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_SubscribeTailServer = grpc.ServerStreamingServer[TailEvent]

// QueryService_ServiceDesc is the grpc.ServiceDesc for QueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lynxdb.cluster.v1.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyPartCommitted",
			Handler:    _QueryService_NotifyPartCommitted_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteQuery",
			Handler:       _QueryService_ExecuteQuery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeTail",
			Handler:       _QueryService_SubscribeTail_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cluster.proto",
}
